version: "3.8"
services:
  webserver:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      target: app
    container_name: nginx-webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
      target: app
    container_name: php-app
    working_dir: /var/www/html
    depends_on:
      - db

  db:
    image: mysql:9.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql/

volumes:
  mysql-data:
