version: "3"
services:
  web:
    build: .
    container_name: web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: phone_shop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro  # Đảm bảo tệp này có quyền 644 và chỉ đọc
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro  # Đảm bảo tệp này chỉ đọc

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
